enum TokenType {
  IDENTIFIER = "IDENTIFIER",
  NUMBER_LITERAL = "NUMBER_LITERAL",
  STRING_LITERAL = "STRING_LITERAL",

  OPEN_PAREN = "OPEN_PAREN",
  CLOSE_PAREN = "CLOSE_PAREN",
  OPEN_BRACE = "OPEN_BRACE",
  CLOSE_BRACE = "CLOSE_BRACE",
  OPEN_BRACKET = "OPEN_BRACKET",
  CLOSE_BRACKET = "CLOSE_BRACKET",

  COMMA = "COMMA",
  SEMICOLON = "SEMICOLON",
  DOT = "DOT",
  COLON = "COLON",
  UNDERSCORE = "UNDERSCORE",
  QUESTION = "QUESTION",

  PLUS = "PLUS",
  INCREMENT = "INCREMENT",
  PLUS_ASSIGN = "PLUS_ASSIGN",

  MINUS = "MINUS",
  DECREMENT = "DECREMENT",
  MINUS_ASSIGN = "MINUS_ASSIGN",

  STAR = "STAR",
  STAR_STAR = "STAR_STAR",
  STAR_ASSIGN = "STAR_ASSIGN",

  SLASH = "SLASH",
  SLASH_SLASH = "SLASH_SLASH",
  SLASH_ASSIGN = "SLASH_ASSIGN",

  PERCENT = "PERCENT",
  PERCENT_ASSIGN = "PERCENT_ASSIGN",

  NOT = "NOT",
  TILDE = "TILDE",
  ASSIGN = "ASSIGN",

  EQUAL = "EQUAL",
  NOT_EQUAL = "NOT_EQUAL",
  LESS_THAN = "LESS_THAN",
  LESS_EQUAL = "LESS_EQUAL",
  GREATER_THAN = "GREATER_THAN",
  GREATER_EQUAL = "GREATER_EQUAL",

  CARET = "CARET", // ^ bitwise XOR
  CARET_ASSIGN = "CARET_ASSIGN",

  AMPERSAND = "AMPERSAND",
  AMPERSAND_ASSIGN = "AMPERSAND_ASSIGN",

  PIPE = "PIPE",
  PIPE_ASSIGN = "PIPE_ASSIGN",

  AND = "AND",
  OR = "OR",
  BITSHIFT_LEFT = "BITSHIFT_LEFT",
  BITSHIFT_RIGHT = "BITSHIFT_RIGHT",

  UNKNOWN = "UNKNOWN",
  NOOP = "NOOP",
  EOF = "EOF",
}

export default TokenType;
