export const BINDGEN_HEADER_NOT_FOUND_CODE = "BPL_BINDGEN_HEADER_NOT_FOUND";
export const BINDGEN_HEADER_SYMLINK_CODE = "BPL_BINDGEN_HEADER_SYMLINK";
export const BINDGEN_HEADER_NOT_FILE_CODE = "BPL_BINDGEN_HEADER_NOT_FILE";
export const BINDGEN_HEADER_PARENT_SYMLINK_CODE =
  "BPL_BINDGEN_HEADER_PARENT_SYMLINK";
export const BINDGEN_OUTPUT_SYMLINK_CODE = "BPL_BINDGEN_OUTPUT_SYMLINK";
export const BINDGEN_OUTPUT_DIRECTORY_CODE = "BPL_BINDGEN_OUTPUT_DIRECTORY";
export const BINDGEN_OUTPUT_NOT_FILE_CODE = "BPL_BINDGEN_OUTPUT_NOT_FILE";
export const BINDGEN_OUTPUT_PARENT_NOT_FOUND_CODE =
  "BPL_BINDGEN_OUTPUT_PARENT_NOT_FOUND";
export const BINDGEN_OUTPUT_PARENT_SYMLINK_CODE =
  "BPL_BINDGEN_OUTPUT_PARENT_SYMLINK";
export const BINDGEN_OUTPUT_PARENT_NOT_DIRECTORY_CODE =
  "BPL_BINDGEN_OUTPUT_PARENT_NOT_DIRECTORY";
export const BINDGEN_FAILED_CODE = "BPL_BINDGEN_FAILED";
export const BINDGEN_JSON_ERROR_CODES = [
  BINDGEN_HEADER_NOT_FOUND_CODE,
  BINDGEN_HEADER_SYMLINK_CODE,
  BINDGEN_HEADER_NOT_FILE_CODE,
  BINDGEN_HEADER_PARENT_SYMLINK_CODE,
  BINDGEN_OUTPUT_SYMLINK_CODE,
  BINDGEN_OUTPUT_DIRECTORY_CODE,
  BINDGEN_OUTPUT_NOT_FILE_CODE,
  BINDGEN_OUTPUT_PARENT_NOT_FOUND_CODE,
  BINDGEN_OUTPUT_PARENT_SYMLINK_CODE,
  BINDGEN_OUTPUT_PARENT_NOT_DIRECTORY_CODE,
  BINDGEN_FAILED_CODE,
] as const;
