export const CHECK_INPUT_NOT_FOUND_CODE = "BPL_CHECK_INPUT_NOT_FOUND";
export const CHECK_INPUT_SYMLINK_CODE = "BPL_CHECK_INPUT_SYMLINK";
export const CHECK_INPUT_NOT_FILE_CODE = "BPL_CHECK_INPUT_NOT_FILE";
export const CHECK_NO_INPUTS_CODE = "BPL_CHECK_NO_INPUTS";
export const CHECK_JSON_ERROR_CODES = [
  CHECK_INPUT_NOT_FOUND_CODE,
  CHECK_INPUT_SYMLINK_CODE,
  CHECK_INPUT_NOT_FILE_CODE,
  CHECK_NO_INPUTS_CODE,
] as const;
