export const CLEAN_WORKDIR_SYMLINK_CODE = "BPL_CLEAN_WORKDIR_SYMLINK";
export const CLEAN_GIT_TRACKED_UNAVAILABLE_CODE =
  "BPL_CLEAN_GIT_TRACKED_UNAVAILABLE";
export const CLEAN_JSON_ERROR_CODES = [
  CLEAN_WORKDIR_SYMLINK_CODE,
  CLEAN_GIT_TRACKED_UNAVAILABLE_CODE,
] as const;
