export const NEW_PROJECT_NAME_PATH_CODE = "BPL_NEW_NAME_PATH";
export const NEW_PROJECT_NAME_INVALID_CODE = "BPL_NEW_NAME_INVALID";
export const NEW_PROJECT_TEMPLATE_INVALID_CODE = "BPL_NEW_TEMPLATE_INVALID";
export const NEW_PROJECT_PATH_EXISTS_DIRECTORY_CODE =
  "BPL_NEW_PATH_EXISTS_DIRECTORY";
export const NEW_PROJECT_PATH_EXISTS_SYMLINK_CODE =
  "BPL_NEW_PATH_EXISTS_SYMLINK";
export const NEW_PROJECT_PATH_EXISTS_NOT_DIRECTORY_CODE =
  "BPL_NEW_PATH_EXISTS_NOT_DIRECTORY";
export const NEW_PROJECT_JSON_ERROR_CODES = [
  NEW_PROJECT_NAME_PATH_CODE,
  NEW_PROJECT_NAME_INVALID_CODE,
  NEW_PROJECT_TEMPLATE_INVALID_CODE,
  NEW_PROJECT_PATH_EXISTS_DIRECTORY_CODE,
  NEW_PROJECT_PATH_EXISTS_SYMLINK_CODE,
  NEW_PROJECT_PATH_EXISTS_NOT_DIRECTORY_CODE,
] as const;
