/**
 * BPL Runtime Support Library
 * 
 * This file provides SUPPLEMENTARY runtime support:
 * - Signal handlers for crashes (SIGSEGV, SIGFPE, SIGILL, SIGABRT)
 * - Stack trace generation using execinfo
 * - Formatted error printing with colors
 * 
 * The core exception handling (defer, try/catch, longjmp) remains in runtime.ll
 * to ensure correct integration with LLVM IR generated by the compiler.
 * 
 * Compile with: clang -c -fPIC -O2 runtime_support.c -o runtime_support.o
 */

#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <signal.h>
#include <stdint.h>
#include <errno.h>
#include <sys/stat.h>
#include <dirent.h>
#include <limits.h>
#include <time.h>

#ifdef __linux__
#include <execinfo.h>
#include <dlfcn.h>
#endif

#ifdef __APPLE__
#include <execinfo.h>
#include <dlfcn.h>
#endif

/* ============ Constants ============ */
#define BPL_MAX_BACKTRACE_FRAMES 64
#define BPL_MAX_STACK_DEPTH 10000

/* ============ External Variables (defined in runtime.ll) ============ */
extern int32_t __bpl_stack_depth;

/* ============ Local State for BPL Stack Trace ============ */
static const char **__bpl_frame_names;
static const char **__bpl_frame_files;
static int32_t *__bpl_frame_lines;

/* Color codes for terminal output */
#define COLOR_RESET   "\033[0m"
#define COLOR_RED     "\033[1;31m"
#define COLOR_YELLOW  "\033[1;33m"
#define COLOR_CYAN    "\033[1;36m"
#define COLOR_GRAY    "\033[0;90m"
#define COLOR_BOLD    "\033[1m"

/* ============ Stack Trace Printing ============ */

static int __bpl_ensure_frame_storage(void) {
    if (__bpl_frame_names && __bpl_frame_files && __bpl_frame_lines) {
        return 1;
    }

    const char **names = (const char **)calloc(BPL_MAX_STACK_DEPTH, sizeof(*names));
    const char **files = (const char **)calloc(BPL_MAX_STACK_DEPTH, sizeof(*files));
    int32_t *lines = (int32_t *)calloc(BPL_MAX_STACK_DEPTH, sizeof(*lines));

    if (!names || !files || !lines) {
        free((void *)names);
        free((void *)files);
        free(lines);
        return 0;
    }

    __bpl_frame_names = names;
    __bpl_frame_files = files;
    __bpl_frame_lines = lines;
    return 1;
}

/**
 * Print native stack trace using backtrace()
 */
void __bpl_print_stack_trace(void) {
#if defined(__linux__) || defined(__APPLE__)
    void *buffer[BPL_MAX_BACKTRACE_FRAMES];
    int nptrs = backtrace(buffer, BPL_MAX_BACKTRACE_FRAMES);
    
    fprintf(stderr, "\n%s=== Stack Trace ===%s\n", COLOR_CYAN, COLOR_RESET);
    
    char **symbols = backtrace_symbols(buffer, nptrs);
    if (symbols == NULL) {
        fprintf(stderr, "  (unable to get symbols)\n");
        return;
    }
    
    /* Skip first few frames (signal handler, runtime functions) */
    int start = 2;
    for (int i = start; i < nptrs; i++) {
        Dl_info info;
        if (dladdr(buffer[i], &info) && info.dli_sname) {
            fprintf(stderr, "  %s[%d]%s %s%s%s + 0x%lx\n", 
                    COLOR_GRAY, i - start, COLOR_RESET,
                    COLOR_BOLD, info.dli_sname, COLOR_RESET,
                    (unsigned long)((char*)buffer[i] - (char*)info.dli_saddr));
        } else {
            fprintf(stderr, "  %s[%d]%s %s\n", 
                    COLOR_GRAY, i - start, COLOR_RESET, 
                    symbols[i]);
        }
    }
    
    free(symbols);
#else
    fprintf(stderr, "  (stack traces not available on this platform)\n");
#endif
}

/**
 * Print BPL-level stack frames if available
 */
void __bpl_print_bpl_stack_trace(void) {
    if (__bpl_stack_depth <= 0) {
        return;
    }
    
    fprintf(stderr, "\n%s=== BPL Call Stack ===%s\n", COLOR_CYAN, COLOR_RESET);
    
    int depth = __bpl_stack_depth;
    if (depth > BPL_MAX_STACK_DEPTH) depth = BPL_MAX_STACK_DEPTH;
    
    for (int i = depth - 1; i >= 0 && i >= depth - 20; i--) {
        const char *name = __bpl_frame_names ? __bpl_frame_names[i] : NULL;
        const char *file = __bpl_frame_files ? __bpl_frame_files[i] : NULL;
        int32_t line = __bpl_frame_lines ? __bpl_frame_lines[i] : 0;
        
        if (name) {
            if (file && line > 0) {
                fprintf(stderr, "  %s[%d]%s %s%s%s at %s:%d\n",
                        COLOR_GRAY, depth - 1 - i, COLOR_RESET,
                        COLOR_BOLD, name, COLOR_RESET,
                        file, line);
            } else {
                fprintf(stderr, "  %s[%d]%s %s%s%s\n",
                        COLOR_GRAY, depth - 1 - i, COLOR_RESET,
                        COLOR_BOLD, name, COLOR_RESET);
            }
        }
    }
    
    if (depth > 20) {
        fprintf(stderr, "  ... %d more frames\n", depth - 20);
    }
}

/**
 * Capture stack frames into an array for error objects
 */
void **__bpl_capture_stack_frames(int *out_depth) {
#if defined(__linux__) || defined(__APPLE__)
    void *buffer[BPL_MAX_BACKTRACE_FRAMES];
    int nptrs = backtrace(buffer, BPL_MAX_BACKTRACE_FRAMES);
    
    /* Skip runtime frames */
    int start = 3;
    int count = nptrs - start;
    if (count < 0) count = 0;
    
    void **frames = (void **)malloc(count * sizeof(void *));
    if (frames) {
        for (int i = 0; i < count; i++) {
            frames[i] = buffer[start + i];
        }
    }
    
    *out_depth = count;
    return frames;
#else
    *out_depth = 0;
    return NULL;
#endif
}

/* ============ Named Frame Tracking (optional enhancement) ============ */

/**
 * Enter a named stack frame (for enhanced stack traces)
 * This supplements the basic __bpl_enter_stack_frame in runtime.ll
 */
void __bpl_enter_stack_frame_named(const char *name, const char *file, int32_t line) {
    int idx = __bpl_stack_depth;
    if (idx < BPL_MAX_STACK_DEPTH && __bpl_ensure_frame_storage()) {
        __bpl_frame_names[idx] = name;
        __bpl_frame_files[idx] = file;
        __bpl_frame_lines[idx] = line;
    }
}

/**
 * Clear frame info on exit
 */
void __bpl_clear_frame_info(void) {
    int idx = __bpl_stack_depth;
    if (
        idx >= 0 &&
        idx < BPL_MAX_STACK_DEPTH &&
        __bpl_frame_names &&
        __bpl_frame_files &&
        __bpl_frame_lines
    ) {
        __bpl_frame_names[idx] = NULL;
        __bpl_frame_files[idx] = NULL;
        __bpl_frame_lines[idx] = 0;
    }
}

/* ============ Signal Handlers ============ */

static void signal_handler(int sig, siginfo_t *info, void *context) {
    (void)context;
    
    const char *sig_name = "Unknown signal";
    const char *sig_desc = "";
    
    switch (sig) {
        case SIGSEGV:
            sig_name = "SIGSEGV";
            sig_desc = "Segmentation fault (invalid memory access)";
            break;
        case SIGFPE:
            sig_name = "SIGFPE";
            sig_desc = "Floating point exception";
            break;
        case SIGILL:
            sig_name = "SIGILL";
            sig_desc = "Illegal instruction";
            break;
        case SIGABRT:
            sig_name = "SIGABRT";
            sig_desc = "Aborted";
            break;
        case SIGBUS:
            sig_name = "SIGBUS";
            sig_desc = "Bus error (bad memory alignment)";
            break;
    }
    
    fprintf(stderr, "\n%s╔══════════════════════════════════════════════╗%s\n", COLOR_RED, COLOR_RESET);
    fprintf(stderr, "%s║          RUNTIME ERROR: %-8s          ║%s\n", COLOR_RED, sig_name, COLOR_RESET);
    fprintf(stderr, "%s╚══════════════════════════════════════════════╝%s\n", COLOR_RED, COLOR_RESET);
    fprintf(stderr, "\n%s%s%s\n", COLOR_YELLOW, sig_desc, COLOR_RESET);
    
    if (info && sig == SIGSEGV) {
        fprintf(stderr, "Address: %p\n", info->si_addr);
        if (info->si_addr == NULL) {
            fprintf(stderr, "%sLikely cause: Null pointer dereference%s\n", COLOR_YELLOW, COLOR_RESET);
        }
    }
    
    __bpl_print_bpl_stack_trace();
    __bpl_print_stack_trace();
    
    fprintf(stderr, "\n");
    
    /* Re-raise signal to get core dump */
    signal(sig, SIG_DFL);
    raise(sig);
}

/**
 * Install signal handlers for crash detection
 * Called automatically at program startup via constructor attribute
 */
__attribute__((constructor))
static void __bpl_install_signal_handlers(void) {
    struct sigaction sa;
    memset(&sa, 0, sizeof(sa));
    sa.sa_sigaction = signal_handler;
    sa.sa_flags = SA_SIGINFO | SA_ONSTACK;
    sigemptyset(&sa.sa_mask);
    
    sigaction(SIGSEGV, &sa, NULL);
    sigaction(SIGFPE, &sa, NULL);
    sigaction(SIGILL, &sa, NULL);
    sigaction(SIGABRT, &sa, NULL);
    sigaction(SIGBUS, &sa, NULL);
}

/* ============ Formatted Error Printing ============ */

void __bpl_write_stderr(const char *message) {
    if (message) {
        fputs(message, stderr);
    }
}

/**
 * Print a formatted error box with title
 */
void __bpl_print_error_box(const char *title) {
    fprintf(stderr, "\n%s╔══════════════════════════════════════════════╗%s\n", COLOR_RED, COLOR_RESET);
    fprintf(stderr, "%s║ %-44s ║%s\n", COLOR_RED, title, COLOR_RESET);
    fprintf(stderr, "%s╚══════════════════════════════════════════════╝%s\n", COLOR_RED, COLOR_RESET);
}

/**
 * Print error details
 */
void __bpl_print_error_detail(const char *label, const char *value) {
    if (value) {
        fprintf(stderr, "%s: %s%s%s\n", label, COLOR_BOLD, value, COLOR_RESET);
    }
}

/**
 * Print error location
 */
void __bpl_print_error_location(int32_t line, int32_t col) {
    if (line > 0) {
        fprintf(stderr, "Location: line %d, column %d\n", line, col);
    }
}

/* ============ Panic Function ============ */

__attribute__((noreturn))
void __bpl_panic(const char *message) {
    __bpl_print_error_box("PANIC");
    fprintf(stderr, "\n%s%s%s\n", COLOR_YELLOW, message ? message : "Unrecoverable error", COLOR_RESET);
    
    __bpl_print_bpl_stack_trace();
    __bpl_print_stack_trace();
    
    fprintf(stderr, "\n");
    abort();
}

/* ============ Assertion ============ */

void __bpl_assert(int condition, const char *message, const char *file, int32_t line) {
    if (!condition) {
        __bpl_print_error_box("ASSERTION FAILED");
        
        if (message) {
            fprintf(stderr, "\n%s%s%s\n", COLOR_YELLOW, message, COLOR_RESET);
        }
        if (file) {
            fprintf(stderr, "File: %s, Line: %d\n", file, line);
        }
        
        __bpl_print_bpl_stack_trace();
        __bpl_print_stack_trace();
        
        fprintf(stderr, "\n");
        abort();
    }
}

/* Bounded stdin line input. Status values match std/io.bpl. */
int32_t __bpl_read_line(char *buffer, int32_t capacity, int32_t *length) {
    if (!buffer || capacity <= 0 || !length) return 4;
    *length = 0;
    buffer[0] = '\0';
    int truncated = 0;
    int saw_byte = 0;
    for (;;) {
        int ch = fgetc(stdin);
        if (ch == EOF) {
            if (ferror(stdin)) return 3;
            if (!saw_byte) return 1;
            return truncated ? 2 : 0;
        }
        if (ch == '\n') return truncated ? 2 : 0;
        saw_byte = 1;
        if (*length < capacity - 1) {
            buffer[(*length)++] = (char)ch;
            buffer[*length] = '\0';
        } else {
            truncated = 1;
        }
    }
}

/* Accept existing directories, including directory symlinks, but not files. */
static int __bpl_ensure_directory(const char *path) {
    if (mkdir(path, 0777) == 0) return 0;
    if (errno != EEXIST) return -1;
    struct stat info;
    return stat(path, &info) == 0 && S_ISDIR(info.st_mode) ? 0 : -1;
}

int32_t __bpl_mkdirp(const char *path) {
    if (!path || !*path) return -1;
    size_t size = strlen(path) + 1;
    char *copy = (char *)malloc(size);
    if (!copy) return -1;
    memcpy(copy, path, size);
    int result = 0;
    for (size_t i = 1; i < size - 1; ++i) {
        if (copy[i] == '/' && copy[i - 1] != '/') {
            copy[i] = '\0';
            result = __bpl_ensure_directory(copy);
            copy[i] = '/';
            if (result != 0) break;
        }
    }
    if (result == 0) result = __bpl_ensure_directory(copy);
    free(copy);
    return result;
}

/* Inspect metadata without opening devices or waiting for a FIFO peer. */
int32_t __bpl_path_exists(const char *path) {
    struct stat info;
    return path && stat(path, &info) == 0;
}

/* Keep struct stat and mode constants native. Kinds: other=0, file=1,
 * directory=2, symlink=3. Publish outputs only after all checks succeed. */
int32_t __bpl_file_info(const char *path, int32_t follow_links,
                        int64_t *size, int32_t *kind) {
    if (!size || !kind) return EINVAL;
    *size = 0;
    *kind = 0;
    if (!path || (follow_links != 0 && follow_links != 1)) return EINVAL;
    struct stat info;
    int result = follow_links ? stat(path, &info) : lstat(path, &info);
    if (result != 0) return errno ? errno : EIO;
    if (info.st_size < 0 || (uintmax_t)info.st_size > INT64_MAX) return EOVERFLOW;
    *size = (int64_t)info.st_size;
    if (S_ISREG(info.st_mode)) *kind = 1;
    else if (S_ISDIR(info.st_mode)) *kind = 2;
    else if (S_ISLNK(info.st_mode)) *kind = 3;
    return 0;
}

/* Whole-file buffers fit the stdlib's signed int lengths, with room for NUL.
 * Read streams incrementally: procfs, pipes, and changing files need no seek. */
int32_t __bpl_read_file(const char *path, char **data, int32_t *length) {
    if (!data || !length) return EINVAL;
    *data = NULL;
    *length = 0;
    if (!path) return EINVAL;
    FILE *file = fopen(path, "rb");
    if (!file) return errno ? errno : EIO;
    size_t capacity = 4096, used = 0;
    const size_t limit = INT32_MAX - 1;
    char *buffer = malloc(capacity + 1);
    int error = buffer ? 0 : ENOMEM;
    while (!error) {
        if (used == capacity) {
            /* Probe EOF before rejecting an exactly-at-limit stream. */
            int byte = fgetc(file);
            if (byte == EOF) {
                if (ferror(file)) error = errno ? errno : EIO;
                break;
            }
            if (capacity == limit) { error = EFBIG; break; }
            size_t next = capacity > limit / 2 ? limit : capacity * 2;
            char *grown = realloc(buffer, next + 1);
            if (!grown) { error = ENOMEM; break; }
            buffer = grown;
            capacity = next;
            buffer[used++] = (char)byte;
        }
        size_t count = fread(buffer + used, 1, capacity - used, file);
        used += count;
        if (ferror(file)) { error = errno ? errno : EIO; break; }
        if (feof(file)) break;
        if (!count) { error = EIO; break; }
    }
    if (fclose(file) != 0 && !error) error = errno ? errno : EIO;
    if (error) { free(buffer); return error; }
    buffer[used] = 0;
    *data = buffer;
    *length = (int32_t)used;
    return 0;
}

/* Read into caller-owned storage without seeking or allocating. A failed
 * read may already have consumed bytes and modified the destination buffer. */
int32_t __bpl_file_read(FILE *file, void *data, int32_t length, int32_t *count) {
    if (!count) return EINVAL;
    *count = 0;
    if (!file) return EBADF;
    if (length < 0 || (!data && length)) return EINVAL;
    if (!length) return 0;
    if (ferror(file)) return EIO;
    errno = 0;
    size_t actual = fread(data, 1, (size_t)length, file);
    *count = (int32_t)actual;
    if (ferror(file)) return errno ? errno : EIO;
    return 0;
}

int32_t __bpl_file_write(FILE *file, const void *data, int64_t length) {
    if (!file || length < 0 || (!data && length)) return EINVAL;
    if ((uint64_t)length > SIZE_MAX) return EFBIG;
    size_t written = 0;
    while (written < (size_t)length) {
        size_t count = fwrite((const char *)data + written, 1,
                              (size_t)length - written, file);
        written += count;
        if (ferror(file) || !count) return errno ? errno : EIO;
    }
    return ferror(file) ? EIO : 0;
}

int32_t __bpl_write_file(const char *path, const void *data, int64_t length) {
    if (!path || length < 0 || (!data && length)) return EINVAL;
    FILE *file = fopen(path, "wb");
    if (!file) return errno ? errno : EIO;
    int error = __bpl_file_write(file, data, length);
    if (fclose(file) != 0 && !error) error = errno ? errno : EIO;
    return error;
}

const char *__bpl_dirent_name(const struct dirent *entry) {
    return entry ? entry->d_name : NULL;
}

/* Checked raw storage for BPL-owned entries; their layout stays in BPL. */
int32_t __bpl_fs_allocate_entries(int32_t count, int64_t width, void **data) {
    if (!data) return EINVAL;
    *data = NULL;
    if (count < 0 || width <= 0) return EINVAL;
    if (!count) return 0;
    if ((uint64_t)width > SIZE_MAX / (uint32_t)count) return EOVERFLOW;
    *data = malloc((size_t)count * (size_t)width);
    return *data ? 0 : ENOMEM;
}

void __bpl_free_dir_names(char **names, int32_t count) {
    for (int32_t i = 0; i < count; ++i) free(names[i]);
    free(names);
}

/* Own every name, distinguish EOF from failure, and publish only complete
 * results. No dirent or BPL String layout crosses the native ABI. */
int32_t __bpl_list_dir(const char *path, char ***names, int32_t *count) {
    if (!names || !count) return EINVAL;
    *names = NULL;
    *count = 0;
    if (!path) return EINVAL;
    DIR *dir = opendir(path);
    if (!dir) return errno ? errno : EIO;
    char **entries = NULL;
    size_t used = 0, capacity = 0;
    size_t limit = SIZE_MAX / sizeof(char *);
    if (limit > INT32_MAX) limit = INT32_MAX;
    int error = 0;
    for (;;) {
        errno = 0;
        struct dirent *entry = readdir(dir);
        if (!entry) { error = errno; break; }
        const char *name = entry->d_name;
        if (!strcmp(name, ".") || !strcmp(name, "..")) continue;
        size_t length = strlen(name);
        if (length > INT32_MAX - 1 || used == limit) {
            error = EOVERFLOW;
            break;
        }
        if (used == capacity) {
            size_t next = capacity ? (capacity > limit / 2 ? limit : capacity * 2) : 16;
            if (next > limit) next = limit;
            char **grown = realloc(entries, next * sizeof(char *));
            if (!grown) { error = ENOMEM; break; }
            entries = grown;
            capacity = next;
        }
        char *copy = malloc(length + 1);
        if (!copy) { error = ENOMEM; break; }
        memcpy(copy, name, length + 1);
        entries[used++] = copy;
    }
    errno = 0;
    if (closedir(dir) != 0 && !error) error = errno ? errno : EIO;
    if (error) {
        __bpl_free_dir_names(entries, (int32_t)used);
        return error;
    }
    *names = entries;
    *count = (int32_t)used;
    return 0;
}

/* Avoid exposing platform-specific timespec/timeval layouts to BPL. */
int32_t __bpl_clock(int32_t monotonic, int32_t units, int64_t *result) {
    if (!result || (units != 1 && units != 1000 && units != 1000000)) return EINVAL;
    *result = 0;
    struct timespec now;
    if (clock_gettime(monotonic ? CLOCK_MONOTONIC : CLOCK_REALTIME, &now) != 0)
        return errno ? errno : EIO;
    int64_t seconds = (int64_t)now.tv_sec;
    int64_t fraction = now.tv_nsec / (1000000000 / units);
    if (seconds > INT64_MAX / units || seconds < INT64_MIN / units)
        return EOVERFLOW;
    int64_t whole = seconds * units;
    if (whole > INT64_MAX - fraction) return EOVERFLOW;
    *result = whole + fraction;
    return 0;
}

int32_t __bpl_sleep_us(int64_t microseconds) {
    if (microseconds < 0) return EINVAL;
    struct timespec request;
    int64_t seconds = microseconds / 1000000;
    request.tv_sec = (time_t)seconds;
    if ((int64_t)request.tv_sec != seconds) return EOVERFLOW;
    request.tv_nsec = (long)((microseconds % 1000000) * 1000);
    while (nanosleep(&request, &request) != 0) {
        if (errno != EINTR) return errno ? errno : EIO;
    }
    return 0;
}
