/**
 * BPL Runtime Support Library
 * 
 * This file provides SUPPLEMENTARY runtime support:
 * - Signal handlers for crashes (SIGSEGV, SIGFPE, SIGILL, SIGABRT)
 * - Stack trace generation using execinfo
 * - Formatted error printing with colors
 * 
 * The core exception handling (defer, try/catch, longjmp) remains in runtime.ll
 * to ensure correct integration with LLVM IR generated by the compiler.
 * 
 * Compile with: clang -c -fPIC -O2 runtime_support.c -o runtime_support.o
 */

#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <signal.h>
#include <stdint.h>

#ifdef __linux__
#include <execinfo.h>
#include <dlfcn.h>
#endif

#ifdef __APPLE__
#include <execinfo.h>
#include <dlfcn.h>
#endif

/* ============ Constants ============ */
#define BPL_MAX_BACKTRACE_FRAMES 64
#define BPL_MAX_STACK_DEPTH 10000

/* ============ External Variables (defined in runtime.ll) ============ */
extern int32_t __bpl_stack_depth;

/* ============ Local State for BPL Stack Trace ============ */
static const char **__bpl_frame_names;
static const char **__bpl_frame_files;
static int32_t *__bpl_frame_lines;

/* Color codes for terminal output */
#define COLOR_RESET   "\033[0m"
#define COLOR_RED     "\033[1;31m"
#define COLOR_YELLOW  "\033[1;33m"
#define COLOR_CYAN    "\033[1;36m"
#define COLOR_GRAY    "\033[0;90m"
#define COLOR_BOLD    "\033[1m"

/* ============ Stack Trace Printing ============ */

static int __bpl_ensure_frame_storage(void) {
    if (__bpl_frame_names && __bpl_frame_files && __bpl_frame_lines) {
        return 1;
    }

    const char **names = (const char **)calloc(BPL_MAX_STACK_DEPTH, sizeof(*names));
    const char **files = (const char **)calloc(BPL_MAX_STACK_DEPTH, sizeof(*files));
    int32_t *lines = (int32_t *)calloc(BPL_MAX_STACK_DEPTH, sizeof(*lines));

    if (!names || !files || !lines) {
        free((void *)names);
        free((void *)files);
        free(lines);
        return 0;
    }

    __bpl_frame_names = names;
    __bpl_frame_files = files;
    __bpl_frame_lines = lines;
    return 1;
}

/**
 * Print native stack trace using backtrace()
 */
void __bpl_print_stack_trace(void) {
#if defined(__linux__) || defined(__APPLE__)
    void *buffer[BPL_MAX_BACKTRACE_FRAMES];
    int nptrs = backtrace(buffer, BPL_MAX_BACKTRACE_FRAMES);
    
    fprintf(stderr, "\n%s=== Stack Trace ===%s\n", COLOR_CYAN, COLOR_RESET);
    
    char **symbols = backtrace_symbols(buffer, nptrs);
    if (symbols == NULL) {
        fprintf(stderr, "  (unable to get symbols)\n");
        return;
    }
    
    /* Skip first few frames (signal handler, runtime functions) */
    int start = 2;
    for (int i = start; i < nptrs; i++) {
        Dl_info info;
        if (dladdr(buffer[i], &info) && info.dli_sname) {
            fprintf(stderr, "  %s[%d]%s %s%s%s + 0x%lx\n", 
                    COLOR_GRAY, i - start, COLOR_RESET,
                    COLOR_BOLD, info.dli_sname, COLOR_RESET,
                    (unsigned long)((char*)buffer[i] - (char*)info.dli_saddr));
        } else {
            fprintf(stderr, "  %s[%d]%s %s\n", 
                    COLOR_GRAY, i - start, COLOR_RESET, 
                    symbols[i]);
        }
    }
    
    free(symbols);
#else
    fprintf(stderr, "  (stack traces not available on this platform)\n");
#endif
}

/**
 * Print BPL-level stack frames if available
 */
void __bpl_print_bpl_stack_trace(void) {
    if (__bpl_stack_depth <= 0) {
        return;
    }
    
    fprintf(stderr, "\n%s=== BPL Call Stack ===%s\n", COLOR_CYAN, COLOR_RESET);
    
    int depth = __bpl_stack_depth;
    if (depth > BPL_MAX_STACK_DEPTH) depth = BPL_MAX_STACK_DEPTH;
    
    for (int i = depth - 1; i >= 0 && i >= depth - 20; i--) {
        const char *name = __bpl_frame_names ? __bpl_frame_names[i] : NULL;
        const char *file = __bpl_frame_files ? __bpl_frame_files[i] : NULL;
        int32_t line = __bpl_frame_lines ? __bpl_frame_lines[i] : 0;
        
        if (name) {
            if (file && line > 0) {
                fprintf(stderr, "  %s[%d]%s %s%s%s at %s:%d\n",
                        COLOR_GRAY, depth - 1 - i, COLOR_RESET,
                        COLOR_BOLD, name, COLOR_RESET,
                        file, line);
            } else {
                fprintf(stderr, "  %s[%d]%s %s%s%s\n",
                        COLOR_GRAY, depth - 1 - i, COLOR_RESET,
                        COLOR_BOLD, name, COLOR_RESET);
            }
        }
    }
    
    if (depth > 20) {
        fprintf(stderr, "  ... %d more frames\n", depth - 20);
    }
}

/**
 * Capture stack frames into an array for error objects
 */
void **__bpl_capture_stack_frames(int *out_depth) {
#if defined(__linux__) || defined(__APPLE__)
    void *buffer[BPL_MAX_BACKTRACE_FRAMES];
    int nptrs = backtrace(buffer, BPL_MAX_BACKTRACE_FRAMES);
    
    /* Skip runtime frames */
    int start = 3;
    int count = nptrs - start;
    if (count < 0) count = 0;
    
    void **frames = (void **)malloc(count * sizeof(void *));
    if (frames) {
        for (int i = 0; i < count; i++) {
            frames[i] = buffer[start + i];
        }
    }
    
    *out_depth = count;
    return frames;
#else
    *out_depth = 0;
    return NULL;
#endif
}

/* ============ Named Frame Tracking (optional enhancement) ============ */

/**
 * Enter a named stack frame (for enhanced stack traces)
 * This supplements the basic __bpl_enter_stack_frame in runtime.ll
 */
void __bpl_enter_stack_frame_named(const char *name, const char *file, int32_t line) {
    int idx = __bpl_stack_depth;
    if (idx < BPL_MAX_STACK_DEPTH && __bpl_ensure_frame_storage()) {
        __bpl_frame_names[idx] = name;
        __bpl_frame_files[idx] = file;
        __bpl_frame_lines[idx] = line;
    }
}

/**
 * Clear frame info on exit
 */
void __bpl_clear_frame_info(void) {
    int idx = __bpl_stack_depth;
    if (
        idx >= 0 &&
        idx < BPL_MAX_STACK_DEPTH &&
        __bpl_frame_names &&
        __bpl_frame_files &&
        __bpl_frame_lines
    ) {
        __bpl_frame_names[idx] = NULL;
        __bpl_frame_files[idx] = NULL;
        __bpl_frame_lines[idx] = 0;
    }
}

/* ============ Signal Handlers ============ */

static void signal_handler(int sig, siginfo_t *info, void *context) {
    (void)context;
    
    const char *sig_name = "Unknown signal";
    const char *sig_desc = "";
    
    switch (sig) {
        case SIGSEGV:
            sig_name = "SIGSEGV";
            sig_desc = "Segmentation fault (invalid memory access)";
            break;
        case SIGFPE:
            sig_name = "SIGFPE";
            sig_desc = "Floating point exception";
            break;
        case SIGILL:
            sig_name = "SIGILL";
            sig_desc = "Illegal instruction";
            break;
        case SIGABRT:
            sig_name = "SIGABRT";
            sig_desc = "Aborted";
            break;
        case SIGBUS:
            sig_name = "SIGBUS";
            sig_desc = "Bus error (bad memory alignment)";
            break;
    }
    
    fprintf(stderr, "\n%s╔══════════════════════════════════════════════╗%s\n", COLOR_RED, COLOR_RESET);
    fprintf(stderr, "%s║          RUNTIME ERROR: %-8s          ║%s\n", COLOR_RED, sig_name, COLOR_RESET);
    fprintf(stderr, "%s╚══════════════════════════════════════════════╝%s\n", COLOR_RED, COLOR_RESET);
    fprintf(stderr, "\n%s%s%s\n", COLOR_YELLOW, sig_desc, COLOR_RESET);
    
    if (info && sig == SIGSEGV) {
        fprintf(stderr, "Address: %p\n", info->si_addr);
        if (info->si_addr == NULL) {
            fprintf(stderr, "%sLikely cause: Null pointer dereference%s\n", COLOR_YELLOW, COLOR_RESET);
        }
    }
    
    __bpl_print_bpl_stack_trace();
    __bpl_print_stack_trace();
    
    fprintf(stderr, "\n");
    
    /* Re-raise signal to get core dump */
    signal(sig, SIG_DFL);
    raise(sig);
}

/**
 * Install signal handlers for crash detection
 * Called automatically at program startup via constructor attribute
 */
__attribute__((constructor))
static void __bpl_install_signal_handlers(void) {
    struct sigaction sa;
    memset(&sa, 0, sizeof(sa));
    sa.sa_sigaction = signal_handler;
    sa.sa_flags = SA_SIGINFO | SA_ONSTACK;
    sigemptyset(&sa.sa_mask);
    
    sigaction(SIGSEGV, &sa, NULL);
    sigaction(SIGFPE, &sa, NULL);
    sigaction(SIGILL, &sa, NULL);
    sigaction(SIGABRT, &sa, NULL);
    sigaction(SIGBUS, &sa, NULL);
}

/* ============ Formatted Error Printing ============ */

void __bpl_write_stderr(const char *message) {
    if (message) {
        fputs(message, stderr);
    }
}

/**
 * Print a formatted error box with title
 */
void __bpl_print_error_box(const char *title) {
    fprintf(stderr, "\n%s╔══════════════════════════════════════════════╗%s\n", COLOR_RED, COLOR_RESET);
    fprintf(stderr, "%s║ %-44s ║%s\n", COLOR_RED, title, COLOR_RESET);
    fprintf(stderr, "%s╚══════════════════════════════════════════════╝%s\n", COLOR_RED, COLOR_RESET);
}

/**
 * Print error details
 */
void __bpl_print_error_detail(const char *label, const char *value) {
    if (value) {
        fprintf(stderr, "%s: %s%s%s\n", label, COLOR_BOLD, value, COLOR_RESET);
    }
}

/**
 * Print error location
 */
void __bpl_print_error_location(int32_t line, int32_t col) {
    if (line > 0) {
        fprintf(stderr, "Location: line %d, column %d\n", line, col);
    }
}

/* ============ Panic Function ============ */

__attribute__((noreturn))
void __bpl_panic(const char *message) {
    __bpl_print_error_box("PANIC");
    fprintf(stderr, "\n%s%s%s\n", COLOR_YELLOW, message ? message : "Unrecoverable error", COLOR_RESET);
    
    __bpl_print_bpl_stack_trace();
    __bpl_print_stack_trace();
    
    fprintf(stderr, "\n");
    abort();
}

/* ============ Assertion ============ */

void __bpl_assert(int condition, const char *message, const char *file, int32_t line) {
    if (!condition) {
        __bpl_print_error_box("ASSERTION FAILED");
        
        if (message) {
            fprintf(stderr, "\n%s%s%s\n", COLOR_YELLOW, message, COLOR_RESET);
        }
        if (file) {
            fprintf(stderr, "File: %s, Line: %d\n", file, line);
        }
        
        __bpl_print_bpl_stack_trace();
        __bpl_print_stack_trace();
        
        fprintf(stderr, "\n");
        abort();
    }
}
